variable "ENV" {}

variable "RDS_MYSQL_PORT" {}
variable "RDS_MYSQL_STORAGE" {}
variable "RDS_MYSQL_ENGINE_VERSION" {}
variable "RDS_MYSQL_INSTANCE_CLASS" {}

RDS_MYSQL_PORT           = 3306
RDS_MYSQL_STORAGE        = 10
RDS_MYSQL_ENGINE_VERSION = "5.7"
RDS_MYSQL_INSTANCE_CLASS = "db.t3.micro"